export const AGENT_ERROR_CODES = [
  "INVALID_REQUEST",
  "INPUT_TOO_LARGE",
  "OUTPUT_TOO_LARGE",
  "INTERNAL",
  "ABORTED",
  "INVALID_INPUT",
  "INVALID_OPTIONS",
  "UNSUPPORTED_PROVIDER",
  "PROVIDER_FAILED",
  "PROVIDER_TIMEOUT",
  "PROVIDER_OUTPUT_INVALID",
  "EXPORT_REQUIRES_TERM",
  "EXPORT_INVALID_RESULT",
] as const;

export type AgentErrorCode = (typeof AGENT_ERROR_CODES)[number];
