import { mkdir, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(fileURLToPath(new URL("..", import.meta.url)));
const fixturesRoot = resolve(root, "fixtures");
const args = process.argv.slice(2);
const id = args.find((value) => !value.startsWith("--"));
const kindIndex = args.indexOf("--kind");
const kind = kindIndex >= 0 ? args[kindIndex + 1] : "text";

if (id === undefined || !/^[a-z0-9]+(?:-[a-z0-9]+)*$/u.test(id)) {
  console.error("Usage: pnpm fixture:new <id> [--kind text|csv]");
  process.exitCode = 1;
} else if (kind !== "text" && kind !== "csv") {
  console.error("Fixture kind must be text or csv.");
  process.exitCode = 1;
} else {
  const extension = kind === "csv" ? "csv" : "txt";
  const files = {
    input: resolve(fixturesRoot, "inputs", `${id}.${extension}`),
    expected: resolve(fixturesRoot, "expected", `${id}.json`),
    manifest: resolve(fixturesRoot, "manifests", `${id}.json`),
  };
  try {
    await Promise.all(
      Object.values(files).map((pathname) =>
        writeFile(pathname, "", { flag: "wx" }),
      ),
    );
  } catch (error) {
    console.error(
      error instanceof Error
        ? error.message
        : "Could not create fixture files.",
    );
    process.exitCode = 1;
  }
  if (process.exitCode === undefined) {
    await writeFile(
      files.input,
      kind === "csv"
        ? "title,days,start,end\n"
        : "# Add a synthetic timetable row.\n",
      "utf8",
    );
    await writeFile(
      files.expected,
      `${JSON.stringify({ format: "timetablekit-normalized-v1", TODO: "replace with a verified expected output" }, null, 2)}\n`,
      "utf8",
    );
    await writeFile(
      files.manifest,
      `${JSON.stringify({ id, title: id.replace(/-/g, " "), synthetic: true, visibility: "public", kind, input: `inputs/${id}.${extension}`, expected: `expected/${id}.json`, filename: `${id}.${extension}`, options: { locale: "en-PH", timezone: "Asia/Manila", evidence: "none" }, provenance: "Synthetic data generated by scripts/generate-fixtures.mjs." }, null, 2)}\n`,
      "utf8",
    );
    console.log(
      `Created ${id} fixture scaffolding. Replace the input and expected output before validation.`,
    );
  }
}
